name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_SATELLITE: ${{ secrets.EARTHLY_SATELLITE }}
      EARTHLY_ORG: ${{ secrets.EARTHLY_ORG }}
      FORCE_COLOR: 1

    steps:

    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0

    - uses: actions/checkout@v4

    - name: Run build
      run: 
        set -e
        earthly --ci +vis-build
        tree app/dist

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: app/dist
        clean: true # keep old files if not overridden
        single-commit: true # don't keep history
