name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    timeout-minutes: 35 # earthly satellites time out after 30min
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_SATELLITE: ${{ secrets.EARTHLY_SATELLITE }}
      EARTHLY_ORG: ${{ secrets.EARTHLY_ORG }}
      EARTHLY_CI: true
      GITHUB_ACTIONS: true # Better earthly outputs in github actions
      FORCE_COLOR: 1

    steps:

    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.10

    - uses: actions/checkout@v4

    - name: Test
      run: earthly --auto-skip +ci-test

